"""
MovieMania Database Seeder Command
----------------------------------
Populates the database with 70 diverse, high-quality, real movie entries across
Hollywood, Bollywood (Hindi), and South Indian cinema (Tamil, Telugu, Malayalam, Kannada).
Includes verified metadata, genres, ratings, runtime, directors, cast, and verified poster artwork.
"""

from decimal import Decimal
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from movies.models import Genre, Movie


MOVIE_DATA = [
    {
        "title": 'Inception',
        "overview": 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
        "language": 'English',
        "release_year": 2010,
        "rating": 8.8,
        "runtime_minutes": 148,
        "director": 'Christopher Nolan',
        "cast": 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy, Ken Watanabe',
        "genres": ['Action', 'Adventure', 'Sci-Fi'],
        "mood_tag": 'Mind-Bending',
        "featured": True,
        "poster_url": 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    },
    {
        "title": 'The Dark Knight',
        "overview": 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        "language": 'English',
        "release_year": 2008,
        "rating": 9.0,
        "runtime_minutes": 152,
        "director": 'Christopher Nolan',
        "cast": 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Maggie Gyllenhaal',
        "genres": ['Action', 'Crime', 'Drama'],
        "mood_tag": 'Gripping',
        "featured": True,
        "poster_url": 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    },
    {
        "title": 'Interstellar',
        "overview": 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
        "language": 'English',
        "release_year": 2014,
        "rating": 8.7,
        "runtime_minutes": 169,
        "director": 'Christopher Nolan',
        "cast": 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine, Matt Damon',
        "genres": ['Adventure', 'Drama', 'Sci-Fi'],
        "mood_tag": 'Emotional & Epic',
        "featured": True,
        "poster_url": 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    },
    {
        "title": 'Pulp Fiction',
        "overview": 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        "language": 'English',
        "release_year": 1994,
        "rating": 8.9,
        "runtime_minutes": 154,
        "director": 'Quentin Tarantino',
        "cast": 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Ving Rhames',
        "genres": ['Crime', 'Drama'],
        "mood_tag": 'Cult Classic',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    },
    {
        "title": 'The Matrix',
        "overview": 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
        "language": 'English',
        "release_year": 1999,
        "rating": 8.7,
        "runtime_minutes": 136,
        "director": 'Lana Wachowski, Lilly Wachowski',
        "cast": 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Joe Pantoliano',
        "genres": ['Action', 'Sci-Fi'],
        "mood_tag": 'Mind-Bending',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/l4QHerTSbflURdsWDR5OpEJqaod.jpg',
    },
    {
        "title": 'Oppenheimer',
        "overview": 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
        "language": 'English',
        "release_year": 2023,
        "rating": 8.9,
        "runtime_minutes": 180,
        "director": 'Christopher Nolan',
        "cast": 'Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr., Florence Pugh',
        "genres": ['Biography', 'Drama', 'History'],
        "mood_tag": 'Intense & Dramatic',
        "featured": True,
        "poster_url": 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    },
    {
        "title": 'Fight Club',
        "overview": 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
        "language": 'English',
        "release_year": 1999,
        "rating": 8.8,
        "runtime_minutes": 139,
        "director": 'David Fincher',
        "cast": 'Brad Pitt, Edward Norton, Helena Bonham Carter, Meat Loaf, Jared Leto',
        "genres": ['Drama', 'Thriller'],
        "mood_tag": 'Psychological Thriller',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    },
    {
        "title": 'The Shawshank Redemption',
        "overview": 'A banker convicted of uxoricide forms a friendship over a quarter of a century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.',
        "language": 'English',
        "release_year": 1994,
        "rating": 9.3,
        "runtime_minutes": 142,
        "director": 'Frank Darabont',
        "cast": 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler, Clancy Brown',
        "genres": ['Drama'],
        "mood_tag": 'Inspiring',
        "featured": True,
        "poster_url": 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    },
    {
        "title": 'Whiplash',
        "overview": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
        "language": 'English',
        "release_year": 2014,
        "rating": 8.5,
        "runtime_minutes": 106,
        "director": 'Damien Chazelle',
        "cast": 'Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist, Austin Stowell',
        "genres": ['Drama', 'Music'],
        "mood_tag": 'Electrifying & Tense',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/vNXdHau4u29eUksR2p4YvV06Hlq.jpg',
    },
    {
        "title": 'Gladiator',
        "overview": 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
        "language": 'English',
        "release_year": 2000,
        "rating": 8.5,
        "runtime_minutes": 155,
        "director": 'Ridley Scott',
        "cast": 'Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed, Richard Harris',
        "genres": ['Action', 'Adventure', 'Drama'],
        "mood_tag": 'Heroic Epic',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/b82nqn1Gqz877e8GkXg8kOecKzR.jpg',
    },
    {
        "title": 'Spider-Man: Into the Spider-Verse',
        "overview": 'Teen Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from various parallel dimensions to stop a threat to all reality.',
        "language": 'English',
        "release_year": 2018,
        "rating": 8.4,
        "runtime_minutes": 117,
        "director": 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
        "cast": 'Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali, Nicolas Cage',
        "genres": ['Action', 'Adventure', 'Animation', 'Sci-Fi'],
        "mood_tag": 'Visually Stunning',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7d6o0070O79vGQyJ5j0Z34Vv6z8.jpg',
    },
    {
        "title": 'Dune: Part Two',
        "overview": 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family, facing a choice between love and the fate of the universe.',
        "language": 'English',
        "release_year": 2024,
        "rating": 8.6,
        "runtime_minutes": 166,
        "director": 'Denis Villeneuve',
        "cast": 'Timothée Chalamet, Zendaya, Rebecca Ferguson, Javier Bardem, Austin Butler',
        "genres": ['Action', 'Adventure', 'Sci-Fi'],
        "mood_tag": 'Epic & Majestic',
        "featured": True,
        "poster_url": 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0x2.jpg',
    },
    {
        "title": 'The Godfather',
        "overview": 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
        "language": 'English',
        "release_year": 1972,
        "rating": 9.2,
        "runtime_minutes": 175,
        "director": 'Francis Ford Coppola',
        "cast": 'Marlon Brando, Al Pacino, James Caan, Robert Duvall, Diane Keaton',
        "genres": ['Crime', 'Drama'],
        "mood_tag": 'Timeless Masterpiece',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
    },
    {
        "title": 'Forrest Gump',
        "overview": "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
        "language": 'English',
        "release_year": 1994,
        "rating": 8.8,
        "runtime_minutes": 142,
        "director": 'Robert Zemeckis',
        "cast": 'Tom Hanks, Robin Wright, Gary Sinise, Sally Field, Mykelti Williamson',
        "genres": ['Comedy', 'Drama', 'Romance'],
        "mood_tag": 'Heartwarming & Inspiring',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxSh26999hPpG9.jpg',
    },
    {
        "title": 'Jurassic Park',
        "overview": 'A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the cloned dinosaurs to run loose.',
        "language": 'English',
        "release_year": 1993,
        "rating": 8.2,
        "runtime_minutes": 127,
        "director": 'Steven Spielberg',
        "cast": 'Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough, Bob Peck',
        "genres": ['Action', 'Adventure', 'Sci-Fi'],
        "mood_tag": 'Thrilling Wonder',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/56Wn2k031L2R149F0B3u7e8b6zV.jpg',
    },
    {
        "title": 'The Prestige',
        "overview": 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
        "language": 'English',
        "release_year": 2006,
        "rating": 8.5,
        "runtime_minutes": 130,
        "director": 'Christopher Nolan',
        "cast": 'Christian Bale, Hugh Jackman, Scarlett Johansson, Michael Caine, David Bowie',
        "genres": ['Drama', 'Mystery', 'Sci-Fi'],
        "mood_tag": 'Mind-Bending Rivalry',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7Q0qT6oXm8hS6pQ8a7v6x9YxX5v.jpg',
    },
    {
        "title": 'Se7en',
        "overview": 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
        "language": 'English',
        "release_year": 1995,
        "rating": 8.6,
        "runtime_minutes": 127,
        "director": 'David Fincher',
        "cast": 'Morgan Freeman, Brad Pitt, Kevin Spacey, Gwyneth Paltrow, John C. McGinley',
        "genres": ['Crime', 'Mystery', 'Thriller'],
        "mood_tag": 'Dark & Gripping',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/ba4CpFFZq078jBuhz96n9F59A6p.jpg',
    },
    {
        "title": 'Django Unchained',
        "overview": 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.',
        "language": 'English',
        "release_year": 2012,
        "rating": 8.5,
        "runtime_minutes": 165,
        "director": 'Quentin Tarantino',
        "cast": 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington, Samuel L. Jackson',
        "genres": ['Action', 'Drama', 'Western'],
        "mood_tag": 'High Energy & Revenge',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/2o0vY2q5w8vN4l6z4s7w2x2X9sX.jpg',
    },
    {
        "title": 'Coco',
        "overview": "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
        "language": 'English',
        "release_year": 2017,
        "rating": 8.4,
        "runtime_minutes": 105,
        "director": 'Lee Unkrich, Adrian Molina',
        "cast": 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach',
        "genres": ['Adventure', 'Animation', 'Family', 'Music'],
        "mood_tag": 'Heartwarming & Colorful',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
    },
    {
        "title": 'The Silence of the Lambs',
        "overview": 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
        "language": 'English',
        "release_year": 1991,
        "rating": 8.6,
        "runtime_minutes": 118,
        "director": 'Jonathan Demme',
        "cast": 'Jodie Foster, Anthony Hopkins, Lawrence A. Bonney, Kasi Lemmons, Scott Glenn',
        "genres": ['Crime', 'Drama', 'Horror', 'Thriller'],
        "mood_tag": 'Chilling & Psychological',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/u258HvhHlWz2q2s2X6L7z8w4p9w.jpg',
    },
    {
        "title": 'Knives Out',
        "overview": 'A master detective investigates the death of the patriarch of an eccentric, combative family.',
        "language": 'English',
        "release_year": 2019,
        "rating": 7.9,
        "runtime_minutes": 130,
        "director": 'Rian Johnson',
        "cast": 'Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis, Michael Shannon',
        "genres": ['Comedy', 'Crime', 'Mystery'],
        "mood_tag": 'Clever Whodunit',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/Ab8mkHmkYADjU7w6MaCpiNZOFv2.jpg',
    },
    {
        "title": 'Top Gun: Maverick',
        "overview": "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on an impossible mission.",
        "language": 'English',
        "release_year": 2022,
        "rating": 8.3,
        "runtime_minutes": 130,
        "director": 'Joseph Kosinski',
        "cast": 'Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm, Glen Powell',
        "genres": ['Action', 'Drama'],
        "mood_tag": 'High-Octane Adrenaline',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/AaV1YIdWKnjAiaOe8UUKBFm327v.jpg',
    },
    {
        "title": 'La La Land',
        "overview": 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
        "language": 'English',
        "release_year": 2016,
        "rating": 8.0,
        "runtime_minutes": 128,
        "director": 'Damien Chazelle',
        "cast": 'Ryan Gosling, Emma Stone, Rosemarie DeWitt, J.K. Simmons, John Legend',
        "genres": ['Comedy', 'Drama', 'Music', 'Romance'],
        "mood_tag": 'Bittersweet Romance',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMDllYjliOTUtMDJjZC00ODIzLWJmNGMtOWI2NzQxMjA2NzdlXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/qJeU79m40j0p6G6K7N4x4LqBq6P.jpg',
    },
    {
        "title": 'The Grand Budapest Hotel',
        "overview": "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
        "language": 'English',
        "release_year": 2014,
        "rating": 8.1,
        "runtime_minutes": 99,
        "director": 'Wes Anderson',
        "cast": 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody, Willem Dafoe',
        "genres": ['Adventure', 'Comedy', 'Crime'],
        "mood_tag": 'Whimsical & Stylish',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/6K273Ff4r95K8q7o0mHlZ8e6yXJ.jpg',
    },
    {
        "title": 'Alien',
        "overview": 'The crew of a commercial spacecraft encounters a deadly lifeform after investigating a mysterious transmission of unknown origin.',
        "language": 'English',
        "release_year": 1979,
        "rating": 8.5,
        "runtime_minutes": 117,
        "director": 'Ridley Scott',
        "cast": 'Sigourney Weaver, Tom Skerritt, John Hurt, Veronica Cartwright, Harry Dean Stanton',
        "genres": ['Horror', 'Sci-Fi'],
        "mood_tag": 'Claustrophobic Terror',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/AmR3JG1DYz5kZ96uGqL8K3eJ7X7.jpg',
    },
    {
        "title": 'Everything Everywhere All at Once',
        "overview": 'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.',
        "language": 'English',
        "release_year": 2022,
        "rating": 7.8,
        "runtime_minutes": 139,
        "director": 'Daniel Kwan, Daniel Scheinert',
        "cast": 'Michelle Yeoh, Stephanie Hsu, Ke Huy Quan, James Hong, Jamie Lee Curtis',
        "genres": ['Action', 'Adventure', 'Comedy', 'Sci-Fi'],
        "mood_tag": 'Mind-Bending & Absurdist',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BOWNmMzAzZmQtNDQ1NC00Nzk5LTkyMmUtNGI2N2NkOWM4MzEyXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/606vV8f8f0w9x8x9g8p7a6v6r4z.jpg',
    },
    {
        "title": 'Avengers: Endgame',
        "overview": "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions.",
        "language": 'English',
        "release_year": 2019,
        "rating": 8.4,
        "runtime_minutes": 181,
        "director": 'Anthony Russo, Joe Russo',
        "cast": 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson',
        "genres": ['Action', 'Adventure', 'Sci-Fi'],
        "mood_tag": 'Epic Superhero Finale',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1z9qE9p8r0K3xU.jpg',
    },
    {
        "title": 'Parasite',
        "overview": 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
        "language": 'Korean',
        "release_year": 2019,
        "rating": 8.5,
        "runtime_minutes": 132,
        "director": 'Bong Joon Ho',
        "cast": 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik, Park So-dam',
        "genres": ['Comedy', 'Drama', 'Thriller'],
        "mood_tag": 'Sharp Social Satire',
        "featured": True,
        "poster_url": 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdEv8aKL0UmQ2.jpg',
    },
    {
        "title": 'Spirited Away',
        "overview": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, a world where humans are changed into beasts.",
        "language": 'Japanese',
        "release_year": 2001,
        "rating": 8.6,
        "runtime_minutes": 125,
        "director": 'Hayao Miyazaki',
        "cast": 'Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takashi Naito, Yasuko Sawaguchi',
        "genres": ['Adventure', 'Animation', 'Family', 'Fantasy'],
        "mood_tag": 'Magical & Poetic',
        "featured": False,
        "poster_url": 'https://images.metahub.space/poster/small/tt0245429/img',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/Ab8mkHmkYADjU7w6MaCpiNZOFv2.jpg',
    },
    {
        "title": 'Goodfellas',
        "overview": 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
        "language": 'English',
        "release_year": 1990,
        "rating": 8.7,
        "runtime_minutes": 145,
        "director": 'Martin Scorsese',
        "cast": 'Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco, Paul Sorvino',
        "genres": ['Biography', 'Crime', 'Drama'],
        "mood_tag": 'High Energy Gangster',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/sw7mordbZxgITU877yTpZCud90M.jpg',
    },
    {
        "title": '3 Idiots',
        "overview": "Two friends embark on a quest for a lost buddy. On this journey, they reminisce about their college days and remember their third friend who inspired them to think differently, even as the rest of the world called them 'idiots'.",
        "language": 'Hindi',
        "release_year": 2009,
        "rating": 8.4,
        "runtime_minutes": 170,
        "director": 'Rajkumar Hirani',
        "cast": 'Aamir Khan, Madhavan, Sharman Joshi, Kareena Kapoor, Boman Irani',
        "genres": ['Comedy', 'Drama'],
        "mood_tag": 'Heartwarming & Inspiring',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BNzc4ZWQ3NmYtODE0Ny00YTQ4LTlkZWItNTBkMGQ0MmUwMmJlXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/uLtVbjNGMuysgFXcLslEZYQv3vl.jpg',
    },
    {
        "title": 'Dangal',
        "overview": 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.',
        "language": 'Hindi',
        "release_year": 2016,
        "rating": 8.3,
        "runtime_minutes": 161,
        "director": 'Nitesh Tiwari',
        "cast": 'Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra, Sakshi Tanwar, Aparshakti Khurana',
        "genres": ['Action', 'Biography', 'Drama', 'Sport'],
        "mood_tag": 'Inspiring & Emotional',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/qJeU79m40j0p6G6K7N4x4LqBq6P.jpg',
    },
    {
        "title": 'Tumbbad',
        "overview": 'A mythological story about a human who builds a shrine for Heramb, a goddess whose curse of greed transforms the lives of three generations of a family in rural Maharashtra.',
        "language": 'Hindi',
        "release_year": 2018,
        "rating": 8.2,
        "runtime_minutes": 104,
        "director": 'Rahi Anil Barve, Anand Gandhi',
        "cast": 'Sohum Shah, Jyoti Malshe, Anita Date, Ronjini Chakraborty, Deepak Damle',
        "genres": ['Drama', 'Fantasy', 'Horror', 'Mystery'],
        "mood_tag": 'Atmospheric & Haunting',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BOTY0YzY3MTMtOWQ5Yi00ODY2LThhOGMtMzFlMjhlODcxOGU1XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1z9qE9p8r0K3xU.jpg',
    },
    {
        "title": 'Gangs of Wasseypur',
        "overview": 'A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, and ignites a deadly, generation-spanning blood feud over coal mines and power.',
        "language": 'Hindi',
        "release_year": 2012,
        "rating": 8.2,
        "runtime_minutes": 321,
        "director": 'Anurag Kashyap',
        "cast": 'Manoj Bajpayee, Nawazuddin Siddiqui, Richa Chadha, Tigmanshu Dhulia, Huma Qureshi',
        "genres": ['Action', 'Crime', 'Drama'],
        "mood_tag": 'Raw & Gritty',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BNWQyMmJkYTItNDUyYS00MjgwLWFmYjUtOWQ1NmRjOGZlOTZhXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/ba4CpFFZq078jBuhz96n9F59A6p.jpg',
    },
    {
        "title": 'Andhadhun',
        "overview": 'A series of mysterious events change the life of a blind pianist, who now must report a murder that he never officially witnessed.',
        "language": 'Hindi',
        "release_year": 2018,
        "rating": 8.2,
        "runtime_minutes": 139,
        "director": 'Sriram Raghavan',
        "cast": 'Ayushmann Khurrana, Tabu, Radhika Apte, Anil Dhawan, Manav Vij',
        "genres": ['Comedy', 'Crime', 'Mystery', 'Thriller'],
        "mood_tag": 'Twisted & Thrilling',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BZjc5OWIzOTgtMmM2ZS00ZjZhLTkyZWItMTFjYTc0NWQ4NzhkXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    },
    {
        "title": 'Swades',
        "overview": 'A successful Indian scientist working at NASA returns to an Indian village to find his childhood nanny, only to discover the profound beauty and systemic challenges of rural India.',
        "language": 'Hindi',
        "release_year": 2004,
        "rating": 8.2,
        "runtime_minutes": 210,
        "director": 'Ashutosh Gowariker',
        "cast": 'Shah Rukh Khan, Gayatri Joshi, Kishori Ballal, Smit Sheth, Lekh Tandon',
        "genres": ['Drama'],
        "mood_tag": 'Inspiring & Soulful',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BOTY3OTBjMGItNzAzMC00MDQ3LTliZjUtMWIyMjk1NDZjNTQ4XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/uLtVbjNGMuysgFXcLslEZYQv3vl.jpg',
    },
    {
        "title": 'Zindagi Na Milegi Dobara',
        "overview": 'Three friends decide to turn their fantasy vacation into reality after one of their friends gets engaged, embarking on an unforgettable road trip across Spain that heals old wounds.',
        "language": 'Hindi',
        "release_year": 2011,
        "rating": 8.2,
        "runtime_minutes": 155,
        "director": 'Zoya Akhtar',
        "cast": 'Hrithik Roshan, Farhan Akhtar, Abhay Deol, Katrina Kaif, Kalki Koechlin',
        "genres": ['Comedy', 'Drama', 'Romance'],
        "mood_tag": 'Feel-Good & Wanderlust',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BOGIzYzg5NzItNDRkYS00NmIzLTk3NzQtZWYwY2VlZDhiYWQ4XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxSh26999hPpG9.jpg',
    },
    {
        "title": 'Taare Zameen Par',
        "overview": 'An eight-year-old boy is thought to be a lazy trouble-maker, until the new art teacher has the patience and compassion to discover the real problem behind his struggles in school.',
        "language": 'Hindi',
        "release_year": 2007,
        "rating": 8.3,
        "runtime_minutes": 165,
        "director": 'Aamir Khan, Amole Gupte',
        "cast": 'Darsheel Safary, Aamir Khan, Tisca Chopra, Vipin Sharma, Sachet Engineer',
        "genres": ['Drama', 'Family'],
        "mood_tag": 'Heart-Touching & Emotional',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BZTI0ZGRiMDEtNGNjMS00MGU4LWI3OTktNzcxMDZmZTk3MTljXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    },
    {
        "title": 'Lagaan',
        "overview": 'The people of a small village in Victorian India stake their future on a game of cricket against their ruthless British rulers in exchange for cancelling high agricultural taxes.',
        "language": 'Hindi',
        "release_year": 2001,
        "rating": 8.1,
        "runtime_minutes": 224,
        "director": 'Ashutosh Gowariker',
        "cast": 'Aamir Khan, Gracy Singh, Rachel Shelley, Paul Blackthorne, Suhasini Mulay',
        "genres": ['Adventure', 'Drama', 'Sport'],
        "mood_tag": 'Triumphant & Patriotic',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BM2FmODM4OTktOTRjOS00ZTIzLWIzZjAtMDBhOGEzYThkNzMzXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    },
    {
        "title": 'Queen',
        "overview": 'A Delhi girl from a traditional family sets out on a solo honeymoon to Paris and Amsterdam after her fiance calls off their wedding right before the ceremony.',
        "language": 'Hindi',
        "release_year": 2013,
        "rating": 8.1,
        "runtime_minutes": 144,
        "director": 'Vikas Bahl',
        "cast": 'Kangana Ranaut, Rajkummar Rao, Lisa Haydon, Mish Boyko, Jeffrey Ho',
        "genres": ['Comedy', 'Drama'],
        "mood_tag": 'Empowering & Feel-Good',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BZWU0ZWFhODYtMWE5NC00YzNiLWJlZTctMjFhODhjNDdmZjFmXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/qJeU79m40j0p6G6K7N4x4LqBq6P.jpg',
    },
    {
        "title": 'Drishyam',
        "overview": 'Desperate measures are taken by a man who tries to save his family from the dark consequences of an accidental crime involving the son of an Inspector General.',
        "language": 'Hindi',
        "release_year": 2015,
        "rating": 8.2,
        "runtime_minutes": 163,
        "director": 'Nishikant Kamat',
        "cast": 'Ajay Devgn, Shriya Saran, Tabu, Rajat Kapoor, Ishita Dutta',
        "genres": ['Crime', 'Drama', 'Mystery', 'Thriller'],
        "mood_tag": 'Suspenseful & Clever',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BYjMzZTU0NzUtZGQ0MC00Y2M4LWI5ZDUtZjY1YmNjMjNmNmI3XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    },
    {
        "title": 'Stree',
        "overview": 'In the small town of Chanderi, men live in fear of an evil spirit named Stree who abducts men in the night during festivals.',
        "language": 'Hindi',
        "release_year": 2018,
        "rating": 7.5,
        "runtime_minutes": 128,
        "director": 'Amar Kaushik',
        "cast": 'Rajkummar Rao, Shraddha Kapoor, Pankaj Tripathi, Aparshakti Khurana, Abhishek Banerjee',
        "genres": ['Comedy', 'Horror'],
        "mood_tag": 'Spooky & Hilarious',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BODhiZjI1MDMtZjFjOS00NjZiLWI5N2YtZTM2NWIxNmE3MjMzXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1z9qE9p8r0K3xU.jpg',
    },
    {
        "title": 'Sholay',
        "overview": 'After his family is murdered by a notorious bandit, a former police officer enlists the services of two outlaws to capture him.',
        "language": 'Hindi',
        "release_year": 1975,
        "rating": 8.1,
        "runtime_minutes": 204,
        "director": 'Ramesh Sippy',
        "cast": 'Dharmendra, Sanjeev Kumar, Hema Malini, Amitabh Bachchan, Jaya Bhaduri, Amjad Khan',
        "genres": ['Action', 'Adventure', 'Comedy', 'Drama'],
        "mood_tag": 'Iconic Bollywood Classic',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BNmI1NTRmMWQtNDJlZC00MGIzLWEwYzctYTQwNTI2NWNjM2MwXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    },
    {
        "title": '12th Fail',
        "overview": "Based on the real-life story of IPS Officer Manoj Kumar Sharma, who fearlessly restarts his academic journey and beats all odds to crack the country's most competitive exam.",
        "language": 'Hindi',
        "release_year": 2023,
        "rating": 8.9,
        "runtime_minutes": 147,
        "director": 'Vidhu Vinod Chopra',
        "cast": 'Vikrant Massey, Medha Shankr, Anant V Joshi, Anshumaan Pushkar, Geeta Agrawal',
        "genres": ['Biography', 'Drama'],
        "mood_tag": 'Inspiring & Emotional',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BNTE3OTIxZDYtNjA0NC00N2YxLTg1NGQtOTYxNmZkMDkwOWNjXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/uLtVbjNGMuysgFXcLslEZYQv3vl.jpg',
    },
    {
        "title": 'Barfi!',
        "overview": "Set in the 1970s, the story of three young people who learn that love can neither be defined nor contained by society's definition of normal, as a mute boy forms bonds with two distinct women.",
        "language": 'Hindi',
        "release_year": 2012,
        "rating": 8.1,
        "runtime_minutes": 151,
        "director": 'Anurag Basu',
        "cast": "Ranbir Kapoor, Priyanka Chopra, Ileana D'Cruz, Saurabh Shukla, Ashish Vidyarthi",
        "genres": ['Comedy', 'Drama', 'Romance'],
        "mood_tag": 'Charming & Melodic',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMTQzMTEyODY2Ml5BMl5BanBnXkFtZTgwMjA0MDUyMjE@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/qJeU79m40j0p6G6K7N4x4LqBq6P.jpg',
    },
    {
        "title": 'Hera Pheri',
        "overview": 'Three unemployed men look for answers to all their money problems by involving themselves in a kidnap ransom plan gone wrong.',
        "language": 'Hindi',
        "release_year": 2000,
        "rating": 8.1,
        "runtime_minutes": 156,
        "director": 'Priyadarshan',
        "cast": 'Akshay Kumar, Suniel Shetty, Paresh Rawal, Tabu, Om Puri',
        "genres": ['Comedy', 'Crime'],
        "mood_tag": 'Laugh-Out-Loud Comedy',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BNDZmMGEwMjQtNjFlNi00ZGIxLTlkZjItNmU3Mzg4Y2E0ZjUzXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxSh26999hPpG9.jpg',
    },
    {
        "title": 'Dilwale Dulhania Le Jayenge',
        "overview": "When Raj meets Simran in Europe, it isn't love at first sight but when Simran moves to India for an arranged marriage, love takes its true shape and Raj follows her to win over her family.",
        "language": 'Hindi',
        "release_year": 1995,
        "rating": 8.0,
        "runtime_minutes": 189,
        "director": 'Aditya Chopra',
        "cast": 'Shah Rukh Khan, Kajol, Amrish Puri, Farida Jalal, Anupam Kher',
        "genres": ['Drama', 'Romance'],
        "mood_tag": 'Romantic Classic',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    },
    {
        "title": 'PK',
        "overview": 'An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the world to reconsider religion and dogma.',
        "language": 'Hindi',
        "release_year": 2014,
        "rating": 8.1,
        "runtime_minutes": 153,
        "director": 'Rajkumar Hirani',
        "cast": 'Aamir Khan, Anushka Sharma, Sushant Singh Rajput, Boman Irani, Saurabh Shukla',
        "genres": ['Comedy', 'Drama', 'Sci-Fi'],
        "mood_tag": 'Thought-Provoking & Satirical',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMTYzOTE2NjkxN15BMl5BanBnXkFtZTgwMDgzMTg0MzE@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/uLtVbjNGMuysgFXcLslEZYQv3vl.jpg',
    },
    {
        "title": 'Chak De! India',
        "overview": "Kabir Khan, a former hockey star tainted with false accusations of treachery, tries to redeem himself by coaching the under-equipped, neglected Indian Women's National Hockey Team.",
        "language": 'Hindi',
        "release_year": 2007,
        "rating": 8.1,
        "runtime_minutes": 153,
        "director": 'Shimit Amin',
        "cast": 'Shah Rukh Khan, Vidya Malvade, Sagarika Ghatge, Shilpa Shukla, Tanya Abrol',
        "genres": ['Drama', 'Family', 'Sport'],
        "mood_tag": 'Thrilling & Patriotic',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMjYyOTdmYTYtYjQ4Ni00ZmFiLWJlZjYtZmJkNDI5MmNlNjMyXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    },
    {
        "title": 'Munna Bhai M.B.B.S.',
        "overview": "A lovable gangster sets out to fulfill his father's dream of becoming a doctor, using unorthodox methods and empathy to transform a rigid medical college.",
        "language": 'Hindi',
        "release_year": 2003,
        "rating": 8.1,
        "runtime_minutes": 156,
        "director": 'Rajkumar Hirani',
        "cast": 'Sanjay Dutt, Arshad Warsi, Gracy Singh, Sunil Dutt, Boman Irani',
        "genres": ['Comedy', 'Drama'],
        "mood_tag": 'Warm & Uplifting',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMDE3ZDYzZDctOWJiYS00MTE5LTk0NzgtOThhZTRmZDQ2ZmFjXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxSh26999hPpG9.jpg',
    },
    {
        "title": 'Article 15',
        "overview": 'In rural north India, an upright city-bred IPS officer investigates the gruesome disappearance and murder of three young girls from a marginalized caste.',
        "language": 'Hindi',
        "release_year": 2019,
        "rating": 8.1,
        "runtime_minutes": 130,
        "director": 'Anubhav Sinha',
        "cast": 'Ayushmann Khurrana, Nassar, Manoj Pahwa, Kumud Mishra, Isha Talwar',
        "genres": ['Crime', 'Drama', 'Mystery'],
        "mood_tag": 'Hard-Hitting & Intense',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BYmNlMWYzN2MtODNhOC00ZTdhLTk3NzAtNzRkMTg3MWE4ZmJhXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    },
    {
        "title": 'Haider',
        "overview": "A young man returns to Kashmir amid political turmoil to seek answers about his father's disappearance and is drawn into the politics of the state.",
        "language": 'Hindi',
        "release_year": 2014,
        "rating": 8.0,
        "runtime_minutes": 160,
        "director": 'Vishal Bhardwaj',
        "cast": 'Shahid Kapoor, Tabu, Kay Kay Menon, Shraddha Kapoor, Irrfan Khan',
        "genres": ['Action', 'Crime', 'Drama'],
        "mood_tag": 'Poetic Tragedy',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMjA1NTEwMDMxMF5BMl5BanBnXkFtZTgwODkzMzI0MjE@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/ba4CpFFZq078jBuhz96n9F59A6p.jpg',
    },
    {
        "title": 'Bajrangi Bhaijaan',
        "overview": 'An Indian man with a magnanimous heart takes a young mute Pakistani girl back to her homeland to reunite her with her family.',
        "language": 'Hindi',
        "release_year": 2015,
        "rating": 8.1,
        "runtime_minutes": 163,
        "director": 'Kabir Khan',
        "cast": 'Salman Khan, Harshaali Malhotra, Nawazuddin Siddiqui, Kareena Kapoor',
        "genres": ['Action', 'Adventure', 'Comedy', 'Drama'],
        "mood_tag": 'Emotional & Heartwarming',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BYzVjMjZiNGUtZjZiNy00Yzg4LWEzYzYtMmI1NDg5NWNiNjUwXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/uLtVbjNGMuysgFXcLslEZYQv3vl.jpg',
    },
    {
        "title": 'Kantara',
        "overview": "When greed paves the way for betrayal, scheming and murder, a young tribal man reluctantly embraces his ancestors' spiritual legacy to protect his village.",
        "language": 'Kannada',
        "release_year": 2022,
        "rating": 8.2,
        "runtime_minutes": 148,
        "director": 'Rishab Shetty',
        "cast": 'Rishab Shetty, Sapthami Gowda, Kishore Kumar G., Achyuth Kumar',
        "genres": ['Action', 'Adventure', 'Drama'],
        "mood_tag": 'Folklore & Visceral',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BY2VkZjk5ZjMtM2ExOS00ZDA1LTg1ZDEtYTliNGZiYTc4ZWZiXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    },
    {
        "title": 'RRR',
        "overview": 'A fearless revolutionary and an officer in the British force, who once shared a deep friendship, decide to join forces and chart an inspirational path of freedom against the despotic British rule.',
        "language": 'Telugu',
        "release_year": 2022,
        "rating": 7.8,
        "runtime_minutes": 187,
        "director": 'S.S. Rajamouli',
        "cast": 'N.T. Rama Rao Jr., Ram Charan, Ajay Devgn, Alia Bhatt, Shriya Saran',
        "genres": ['Action', 'Drama'],
        "mood_tag": 'High-Octane Spectacle',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BNWMwODYyMjQtMTczMi00NTQ1LWFkYjItMGJhMWRkY2E3NDAyXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/AaV1YIdWKnjAiaOe8UUKBFm327v.jpg',
    },
    {
        "title": 'Baahubali 2: The Conclusion',
        "overview": 'When Shiva, the son of Bahubali, learns about his royal heritage, he embarks on a quest to find answers and bring justice to the kingdom of Mahishmati.',
        "language": 'Telugu',
        "release_year": 2017,
        "rating": 8.2,
        "runtime_minutes": 167,
        "director": 'S.S. Rajamouli',
        "cast": 'Prabhas, Rana Daggubati, Anushka Shetty, Tamannaah Bhatia, Ramya Krishnan',
        "genres": ['Action', 'Drama', 'Fantasy'],
        "mood_tag": 'Majestic Grandeur',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BNTRhYTlhZTgtYmMyYy00NWI4LTk4MzItOWM2YjBmYTg2OTI2XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/b82nqn1Gqz877e8GkXg8kOecKzR.jpg',
    },
    {
        "title": 'K.G.F: Chapter 2',
        "overview": "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes. While his allies look up to him, the government sees him as a threat to law and order.",
        "language": 'Kannada',
        "release_year": 2022,
        "rating": 8.2,
        "runtime_minutes": 168,
        "director": 'Prashanth Neel',
        "cast": 'Yash, Sanjay Dutt, Raveena Tandon, Srinidhi Shetty, Prakash Raj',
        "genres": ['Action', 'Crime', 'Drama'],
        "mood_tag": 'Mass Action & Powerful',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BZmQzZjVkZTUtYjI4ZC00ZDJmLWI0ZDUtZTFmMGM1Mzc5ZjIyXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    },
    {
        "title": 'Vikram',
        "overview": 'A high-ranking special agent investigates a string of murders conducted by a masked gang of serial killers, uncovering a vast narcotics cartel in the process.',
        "language": 'Tamil',
        "release_year": 2022,
        "rating": 8.3,
        "runtime_minutes": 175,
        "director": 'Lokesh Kanagaraj',
        "cast": 'Kamal Haasan, Vijay Sethupathi, Fahadh Faasil, Suriya, Narain',
        "genres": ['Action', 'Crime', 'Thriller'],
        "mood_tag": 'Adrenaline Rush & Stylish',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMmViYjExY2UtMzZjOS00OGQ2LWEzNWYtNGYxY2NkY2RmMDE3XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    },
    {
        "title": 'Manjummel Boys',
        "overview": 'A group of young friends from a small town in Kerala embark on a trip to Kodaikanal, where an unexpected mishap deep inside the treacherous Guna Caves tests their bond.',
        "language": 'Malayalam',
        "release_year": 2024,
        "rating": 8.4,
        "runtime_minutes": 135,
        "director": 'Chidambaram',
        "cast": 'Soubin Shahir, Sreenath Bhasi, Balu Varghese, Ganapathi, Jean Paul Lal',
        "genres": ['Adventure', 'Drama', 'Thriller'],
        "mood_tag": 'Edge-of-the-Seat Survival',
        "featured": True,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMDVkOGEzZDgtYWU4Yi00MDA3LWE4YmQtYjQxNDgwNDYxNGU4XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0x2.jpg',
    },
    {
        "title": 'Jai Bhim',
        "overview": 'When a courageous tribal man is framed and goes missing from police custody, an idealistic human rights lawyer battles against state-sanctioned injustice to seek truth.',
        "language": 'Tamil',
        "release_year": 2021,
        "rating": 8.8,
        "runtime_minutes": 164,
        "director": 'T.J. Gnanavel',
        "cast": 'Suriya, Lijomol Jose, Manikandan, Rajisha Vijayan, Prakash Raj',
        "genres": ['Crime', 'Drama', 'Mystery'],
        "mood_tag": 'Powerful & Uncompromising',
        "featured": True,
        "poster_url": 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    },
    {
        "title": 'Asuran',
        "overview": 'A pacified farmer with a violent past flees into the wilderness to protect his hot-headed teenage son from the merciless vengeance of a wealthy upper-caste landlord.',
        "language": 'Tamil',
        "release_year": 2019,
        "rating": 8.4,
        "runtime_minutes": 141,
        "director": 'Vetrimaaran',
        "cast": 'Dhanush, Manju Warrier, Prakash Raj, Pasupathy, Ken Karunas',
        "genres": ['Action', 'Drama'],
        "mood_tag": 'Fierce & Gripping',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BYjgyMGFlNmMtYzkzNy00ZjgyLTljNTItMTg4MmNjYWE5NDM4XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    },
    {
        "title": 'Super Deluxe',
        "overview": 'An unfaithful wife, an estranged father, a rebellious youth, and a priest with crisis of faith find themselves in the most unexpected predicaments on an eventful day in Chennai.',
        "language": 'Tamil',
        "release_year": 2019,
        "rating": 8.3,
        "runtime_minutes": 176,
        "director": 'Thiagarajan Kumararaja',
        "cast": 'Vijay Sethupathi, Fahadh Faasil, Samantha Ruth Prabhu, Ramya Krishnan, Mysskin',
        "genres": ['Crime', 'Drama', 'Thriller'],
        "mood_tag": 'Bold & Quirky',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BZmQ3NjM2OWMtY2IxNy00OWY4LWIyYjMtNGUzMGU3ZTZkMWJmXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/ba4CpFFZq078jBuhz96n9F59A6p.jpg',
    },
    {
        "title": '777 Charlie',
        "overview": 'Dharma is a reclusive, lonely man stuck in a mundane life until a spirited, energetic Labrador puppy enters his life and leads him on an extraordinary journey of redemption.',
        "language": 'Kannada',
        "release_year": 2022,
        "rating": 8.7,
        "runtime_minutes": 164,
        "director": 'Kiranraj K',
        "cast": 'Rakshit Shetty, Sangeetha Sringeri, Raj B. Shetty, Danish Sait, Bobby Simha',
        "genres": ['Adventure', 'Comedy', 'Drama'],
        "mood_tag": 'Heartwarming & Pure',
        "featured": False,
        "poster_url": 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/uLtVbjNGMuysgFXcLslEZYQv3vl.jpg',
    },
    {
        "title": 'Drishyam 2',
        "overview": 'Six years after the events of the first film, Georgekutty and his family are still coping with their past secret as a new, meticulous police investigation closes in around them.',
        "language": 'Malayalam',
        "release_year": 2021,
        "rating": 8.4,
        "runtime_minutes": 153,
        "director": 'Jeethu Joseph',
        "cast": 'Mohanlal, Meena, Ansiba Hassan, Esther Anil, Asha Sharath',
        "genres": ['Crime', 'Drama', 'Thriller'],
        "mood_tag": 'Masterful Suspense',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BM2Q2YTczM2QtNDBkNC00M2I5LTkyMzgtOTMwNzQ0N2UyYWQ0XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    },
    {
        "title": 'Kumbalangi Nights',
        "overview": 'Four brothers who share a love-hate relationship live together in a dilapidated house in the serene backwaters of Kumbalangi. When romance enters their lives, their bond is tested and renewed.',
        "language": 'Malayalam',
        "release_year": 2019,
        "rating": 8.5,
        "runtime_minutes": 135,
        "director": 'Madhu C. Narayanan',
        "cast": 'Shane Nigam, Soubin Shahir, Fahadh Faasil, Sreenath Bhasi, Anna Ben',
        "genres": ['Comedy', 'Drama', 'Romance'],
        "mood_tag": 'Heartfelt & Grounded',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMWE2NTAyZjEtOTNlZC00Y2NkLTgxMDEtNGJmNmU4MzJhODU0XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxSh26999hPpG9.jpg',
    },
    {
        "title": 'Kaithi',
        "overview": 'A recently released prisoner on his way to see his daughter for the first time is compelled to drive a truck full of poisoned cops to safety through a siege by drug cartels.',
        "language": 'Tamil',
        "release_year": 2019,
        "rating": 8.4,
        "runtime_minutes": 145,
        "director": 'Lokesh Kanagaraj',
        "cast": 'Karthi, Narain, Arjun Das, Harish Uthaman, Dheena',
        "genres": ['Action', 'Crime', 'Thriller'],
        "mood_tag": 'Non-Stop Action & Suspense',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BOTA1NDc5ZDQtNmM5NC00ZjFjLTliMjAtNGQyMDg5YjU2ZTY4XkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    },
    {
        "title": 'Mahanati',
        "overview": 'The life story of legendary South Indian cinema actress Savitri, chronicling her dramatic rise to superstardom and subsequent tragic fall.',
        "language": 'Telugu',
        "release_year": 2018,
        "rating": 8.4,
        "runtime_minutes": 177,
        "director": 'Nag Ashwin',
        "cast": 'Keerthy Suresh, Dulquer Salmaan, Samantha Ruth Prabhu, Vijay Deverakonda, Rajendra Prasad',
        "genres": ['Biography', 'Drama'],
        "mood_tag": 'Nostalgic & Poignant',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BYmU3ZjM1NTgtYjc2Mi00YzNjLWE1OWQtMjk5MDM4MmU3ZjZjXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/uLtVbjNGMuysgFXcLslEZYQv3vl.jpg',
    },
    {
        "title": 'Premalu',
        "overview": 'Sachin pursues romance in Hyderabad while navigating the highs and lows of ambitious young love and comical misunderstandings.',
        "language": 'Malayalam',
        "release_year": 2024,
        "rating": 7.9,
        "runtime_minutes": 156,
        "director": 'Girish A.D.',
        "cast": 'Naslen, Mamitha Baiju, Shyam Mohan, Sangeeth Prathap, Akhila Bhargavan',
        "genres": ['Comedy', 'Romance'],
        "mood_tag": 'Breezy & Charming',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BZmYzYjA5OTktNTJlMy00NmU2LTk0M2ItOTc2NDlhOTI1ODAzXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxSh26999hPpG9.jpg',
    },
    {
        "title": 'Ponniyin Selvan: Part I',
        "overview": 'Vandiyathevan crosses the Chola land to deliver a crucial message from Crown Prince Aditha Karikalan, as conspiracies against the throne emerge in 10th-century southern India.',
        "language": 'Tamil',
        "release_year": 2022,
        "rating": 7.6,
        "runtime_minutes": 167,
        "director": 'Mani Ratnam',
        "cast": 'Vikram, Aishwarya Rai Bachchan, Jayam Ravi, Karthi, Trisha Krishnan',
        "genres": ['Action', 'Adventure', 'Drama'],
        "mood_tag": 'Historical Epic',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BZWQ0MjExZGMtYWU5Ni00YzIzLWJiOWQtMWIxN2I4ZWM0ZWQwXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/b82nqn1Gqz877e8GkXg8kOecKzR.jpg',
    },
    {
        "title": 'Lucifer',
        "overview": 'A political godfather dies and a lot of thieves dressed in white enter the scene, but a mysterious loyalist steps forward to protect the legacy and maintain balance.',
        "language": 'Malayalam',
        "release_year": 2019,
        "rating": 7.5,
        "runtime_minutes": 174,
        "director": 'Prithviraj Sukumaran',
        "cast": 'Mohanlal, Vivek Oberoi, Manju Warrier, Tovino Thomas, Indrajith Sukumaran',
        "genres": ['Action', 'Crime', 'Drama', 'Thriller'],
        "mood_tag": 'Massive & Political',
        "featured": False,
        "poster_url": 'https://m.media-amazon.com/images/M/MV5BMWY0ZmVjMjctYjFhYy00MDg2LWI1NDItZDk3MzYxODBmZDQwXkEyXkFqcGc@._V1_SX500.jpg',
        "backdrop_url": 'https://image.tmdb.org/t/p/original/ba4CpFFZq078jBuhz96n9F59A6p.jpg',
    },

]


class Command(BaseCommand):
    help = "Populate the MovieMania database with 70 real, curated movie records."

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Delete existing movies and genres before seeding',
        )

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write(self.style.WARNING("Clearing existing movie data..."))
            Movie.objects.all().delete()
            Genre.objects.all().delete()

        self.stdout.write(self.style.NOTICE("Seeding MovieMania movie dataset..."))

        # Pre-seed distinct genres
        all_genre_names = set()
        for item in MOVIE_DATA:
            for g in item.get('genres', []):
                all_genre_names.add(g.strip())

        genre_map = {}
        for g_name in sorted(all_genre_names):
            genre_obj, created = Genre.objects.get_or_create(
                name=g_name,
                defaults={'slug': slugify(g_name)}
            )
            genre_map[g_name] = genre_obj
            if created:
                self.stdout.write(f"  + Created Genre: {g_name}")

        created_count = 0
        updated_count = 0

        for m_data in MOVIE_DATA:
            genre_names = m_data.get('genres', [])
            movie_fields = {
                'overview': m_data['overview'],
                'language': m_data['language'],
                'release_year': m_data['release_year'],
                'rating': Decimal(str(m_data['rating'])),
                'runtime_minutes': m_data['runtime_minutes'],
                'director': m_data['director'],
                'cast': m_data['cast'],
                'poster_url': m_data.get('poster_url', ''),
                'backdrop_url': m_data.get('backdrop_url', ''),
                'mood_tag': m_data.get('mood_tag', ''),
                'featured': m_data.get('featured', False),
            }

            movie_slug = slugify(f"{m_data['title']}-{m_data['release_year']}")
            movie, created = Movie.objects.update_or_create(
                title=m_data['title'],
                release_year=m_data['release_year'],
                defaults={'slug': movie_slug, **movie_fields}
            )

            # Associate genres
            movie.genres.set([genre_map[g] for g in genre_names if g in genre_map])

            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Successfully loaded {created_count + updated_count} movies ({created_count} created, {updated_count} updated) across {len(genre_map)} genres!"
        ))
