# Generated by Django 6.1.1 on 2026-10-07 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('overview', models.TextField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French', 'French')], db_index=True, default='English', max_length=30)),
                ('release_year', models.PositiveIntegerField(db_index=True)),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, help_text='Rating out of 10', max_digits=3)),
                ('runtime_minutes', models.PositiveIntegerField(default=120, help_text='Duration in minutes')),
                ('director', models.CharField(max_length=150)),
                ('cast', models.TextField(help_text='Comma-separated prominent cast members')),
                ('poster_url', models.URLField(blank=True, max_length=600)),
                ('backdrop_url', models.URLField(blank=True, max_length=600)),
                ('mood_tag', models.CharField(blank=True, help_text='e.g. Mind-Bending, Inspiring, Gripping, Uplifting', max_length=100)),
                ('featured', models.BooleanField(default=False, help_text='Highlight on homepage hero/editor picks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-rating', '-release_year'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_watchlist')],
            },
        ),
    ]
